My Project: com.capstone.consumer.utils.GeoUtils Class Reference
com.capstone.consumer.utils.GeoUtils Class Reference
Static Public Member Functions
static Geometry getFlightIntersectionWithNoFlyZone (FlightInformation flightInformation, BaseNoFlyZone noFlyZone)
static boolean flightIsWithinNoFlyZone (FlightInformation flightInformation, BaseNoFlyZone noFlyZone)
static Geometry createCircleGeometry (GeographicCoordinates2D geographicCoordinates2D, double diameterInMeters)
Static Public Attributes
static final GeometryFactory geometryFactory = JTSFactoryFinder.getGeometryFactory()
Member Function Documentation
createCircleGeometry()
static Geometry com.capstone.consumer.utils.GeoUtils.createCircleGeometry (GeographicCoordinates2D geographicCoordinates2D, double diameterInMeters) static
Utility function that help the creation of circular geotools geometries
Parameters
geographicCoordinates2D Center of the circle in geographical coordinates
diameterInMeters diameter in meters of the circle
Returns
a circular geometry
Referenced by com.capstone.shared.bindings.CircularNoFlyZone.getNoFlyZoneBoundariesGeometry().
flightIsWithinNoFlyZone()
static boolean com.capstone.consumer.utils.GeoUtils.flightIsWithinNoFlyZone (FlightInformation flightInformation, BaseNoFlyZone noFlyZone) static
References com.capstone.consumer.utils.GeoUtils.geometryFactory, and com.capstone.shared.bindings.BaseNoFlyZone.getNoFlyZoneBoundariesGeometry().
Referenced by com.capstone.consumer.servicehandler.LiveTrackingService.verityFlightIsInNoFlyZone().
getFlightIntersectionWithNoFlyZone()
static Geometry com.capstone.consumer.utils.GeoUtils.getFlightIntersectionWithNoFlyZone (FlightInformation flightInformation, BaseNoFlyZone noFlyZone) static
References com.capstone.consumer.bindings.FlightInformation.getGeometry(), and com.capstone.shared.bindings.BaseNoFlyZone.getNoFlyZoneBoundariesGeometry().
Referenced by com.capstone.consumer.servicehandler.LiveTrackingService.trackNewNoFlyZone().
Member Data Documentation
geometryFactory
final GeometryFactory com.capstone.consumer.utils.GeoUtils.geometryFactory = JTSFactoryFinder.getGeometryFactory() static
Referenced by com.capstone.consumer.utils.GeoUtils.flightIsWithinNoFlyZone(), com.capstone.consumer.bindings.FlightInformation.getGeometry(), and com.capstone.shared.bindings.PolygonNoFlyZone.getNoFlyZoneBoundariesGeometry().
The documentation for this class was generated from the following file:
C:/Users/Bits McGee/Documents/GitHub/FlightTrackerConsumer/src/main/java/com/capstone/consumer/utils/GeoUtils.java