My Project: com.capstone.shared.bindings.BaseNoFlyZone Class Reference
com.capstone.shared.bindings.BaseNoFlyZone Class Reference abstract
Public Member Functions
String getId ()
abstract Geometry getNoFlyZoneBoundariesGeometry ()
Protected Attributes
float altitude
String notamNumber
Date createdAt
String description
NoFlyZoneType type
Member Function Documentation
getId()
String com.capstone.shared.bindings.BaseNoFlyZone.getId ()
References com.capstone.shared.bindings.BaseNoFlyZone.notamNumber.
Referenced by com.capstone.consumer.servicehandler.NoFlyZoneService.storeNoFlyZone().
getNoFlyZoneBoundariesGeometry()
abstract Geometry com.capstone.shared.bindings.BaseNoFlyZone.getNoFlyZoneBoundariesGeometry () abstract
Reimplemented in com.capstone.shared.bindings.CircularNoFlyZone, and com.capstone.shared.bindings.PolygonNoFlyZone.
Referenced by com.capstone.consumer.utils.GeoUtils.flightIsWithinNoFlyZone(), and com.capstone.consumer.utils.GeoUtils.getFlightIntersectionWithNoFlyZone().
Member Data Documentation
altitude
float com.capstone.shared.bindings.BaseNoFlyZone.altitude protected
createdAt
Date com.capstone.shared.bindings.BaseNoFlyZone.createdAt protected
description
String com.capstone.shared.bindings.BaseNoFlyZone.description protected
notamNumber
String com.capstone.shared.bindings.BaseNoFlyZone.notamNumber protected
Referenced by com.capstone.shared.bindings.BaseNoFlyZone.getId().
type
NoFlyZoneType com.capstone.shared.bindings.BaseNoFlyZone.type protected
The documentation for this class was generated from the following file:
C:/Users/Bits McGee/Documents/GitHub/FlightTrackerConsumer/src/main/java/com/capstone/shared/bindings/BaseNoFlyZone.java