My Project: com.capstone.consumer.servicehandler.LiveTrackingService Class Reference
com.capstone.consumer.servicehandler.LiveTrackingService Class Reference
Public Member Functions
List< FlightInformation > getAllCurrentFlight ()
List< BaseNoFlyZone > getAllNoFlyZones ()
LiveTrackingService (MessagingService messagingService)
void trackNewNoFlyZone (BaseNoFlyZone noFlyZone)
void upsertFlightInformation (FlightInformationKafkaDto newFlightLocation)
void createInternalFlight (FlightInformationKafkaDto flightInformationDto)
void updateFlight (FlightInformationKafkaDto flightInformationKafkaDto)
void verityFlightIsInNoFlyZone (FlightInformation flightInformation)
Constructor & Destructor Documentation
LiveTrackingService()
com.capstone.consumer.servicehandler.LiveTrackingService.LiveTrackingService (MessagingService messagingService)
Member Function Documentation
createInternalFlight()
void com.capstone.consumer.servicehandler.LiveTrackingService.createInternalFlight (FlightInformationKafkaDto flightInformationDto)
Responds to the creation of a new flight received from kafka
Parameters
flightInformationDto information about the new flight that has been created
References com.capstone.consumer.config.MessagingService.sendMessage(), com.capstone.consumer.bindings.FlightInformation.setCheckPoints(), and com.capstone.consumer.servicehandler.LiveTrackingService.verityFlightIsInNoFlyZone().
Referenced by com.capstone.consumer.servicehandler.LiveTrackingService.upsertFlightInformation().
getAllCurrentFlight()
List< FlightInformation > com.capstone.consumer.servicehandler.LiveTrackingService.getAllCurrentFlight ()
Referenced by com.capstone.consumer.controllers.AviationEntities.getFlightInformation().
getAllNoFlyZones()
List< BaseNoFlyZone > com.capstone.consumer.servicehandler.LiveTrackingService.getAllNoFlyZones ()
Referenced by com.capstone.consumer.controllers.AviationEntities.getNoFlyZone().
trackNewNoFlyZone()
void com.capstone.consumer.servicehandler.LiveTrackingService.trackNewNoFlyZone (BaseNoFlyZone noFlyZone)
References com.capstone.consumer.utils.GeoUtils.getFlightIntersectionWithNoFlyZone(), and com.capstone.consumer.config.MessagingService.sendMessage().
Referenced by com.capstone.consumer.kafka.KafkaConsumer.handleCircularNoFlyZone(), and com.capstone.consumer.kafka.KafkaConsumer.handlePolygonNoFlyZone().
updateFlight()
void com.capstone.consumer.servicehandler.LiveTrackingService.updateFlight (FlightInformationKafkaDto flightInformationKafkaDto)
References com.capstone.consumer.config.MessagingService.sendMessage(), and com.capstone.consumer.servicehandler.LiveTrackingService.verityFlightIsInNoFlyZone().
Referenced by com.capstone.consumer.servicehandler.LiveTrackingService.upsertFlightInformation().
upsertFlightInformation()
void com.capstone.consumer.servicehandler.LiveTrackingService.upsertFlightInformation (FlightInformationKafkaDto newFlightLocation)
References com.capstone.consumer.servicehandler.LiveTrackingService.createInternalFlight(), and com.capstone.consumer.servicehandler.LiveTrackingService.updateFlight().
Referenced by com.capstone.consumer.kafka.KafkaConsumer.handleFlightUpdate().
verityFlightIsInNoFlyZone()
void com.capstone.consumer.servicehandler.LiveTrackingService.verityFlightIsInNoFlyZone (FlightInformation flightInformation)
References com.capstone.consumer.utils.GeoUtils.flightIsWithinNoFlyZone(), and com.capstone.consumer.config.MessagingService.sendMessage().
Referenced by com.capstone.consumer.servicehandler.LiveTrackingService.createInternalFlight(), and com.capstone.consumer.servicehandler.LiveTrackingService.updateFlight().
The documentation for this class was generated from the following file:
C:/Users/Bits McGee/Documents/GitHub/FlightTrackerConsumer/src/main/java/com/capstone/consumer/servicehandler/LiveTrackingService.java