My Project: com.capstone.consumer.config.MessagingService Class Reference
com.capstone.consumer.config.MessagingService Class Reference
Public Member Functions
MessagingService (SocketIOServer server)
void sendMessage (SocketMessageInterface socketMessage)
Constructor & Destructor Documentation
MessagingService()
com.capstone.consumer.config.MessagingService.MessagingService (SocketIOServer server)
Member Function Documentation
sendMessage()
void com.capstone.consumer.config.MessagingService.sendMessage (SocketMessageInterface socketMessage)
References com.capstone.consumer.messages.SocketMessageInterface.getName(), and com.capstone.consumer.messages.SocketMessageInterface.getRoom().
Referenced by com.capstone.consumer.servicehandler.LiveTrackingService.createInternalFlight(), com.capstone.consumer.servicehandler.LiveTrackingService.trackNewNoFlyZone(), com.capstone.consumer.servicehandler.LiveTrackingService.updateFlight(), and com.capstone.consumer.servicehandler.LiveTrackingService.verityFlightIsInNoFlyZone().
The documentation for this class was generated from the following file:
C:/Users/Bits McGee/Documents/GitHub/FlightTrackerConsumer/src/main/java/com/capstone/consumer/config/MessagingService.java