My Project: com.capstone.consumer.servicehandler.NoFlyZoneService Class Reference
com.capstone.consumer.servicehandler.NoFlyZoneService Class Reference
Public Member Functions
void storeNoFlyZone (BaseNoFlyZone noFlyZone)
List< BaseNoFlyZone > getNoFlyZones ()
Member Function Documentation
getNoFlyZones()
List< BaseNoFlyZone > com.capstone.consumer.servicehandler.NoFlyZoneService.getNoFlyZones ()
storeNoFlyZone()
void com.capstone.consumer.servicehandler.NoFlyZoneService.storeNoFlyZone (BaseNoFlyZone noFlyZone)
References com.capstone.shared.bindings.BaseNoFlyZone.getId().
Referenced by com.capstone.consumer.kafka.KafkaConsumer.handleCircularNoFlyZone(), and com.capstone.consumer.kafka.KafkaConsumer.handlePolygonNoFlyZone().
The documentation for this class was generated from the following file:
C:/Users/Bits McGee/Documents/GitHub/FlightTrackerConsumer/src/main/java/com/capstone/consumer/servicehandler/NoFlyZoneService.java