My Project: com.capstone.consumer.kafka.KafkaConsumer Class Reference
com.capstone.consumer.kafka.KafkaConsumer Class Reference
Public Member Functions
KafkaConsumer (NoFlyZoneService noFlyZoneService, FlightLocationService flightLocationService, LiveTrackingService collisionListenerService)
void handleCircularNoFlyZone (String message)
void handlePolygonNoFlyZone (String message)
void handleFlightUpdate (String message)
Detailed Description
This is the class where the kafka consumption gets set up.
Constructor & Destructor Documentation
KafkaConsumer()
com.capstone.consumer.kafka.KafkaConsumer.KafkaConsumer (NoFlyZoneService noFlyZoneService, FlightLocationService flightLocationService, LiveTrackingService collisionListenerService)
Member Function Documentation
handleCircularNoFlyZone()
void com.capstone.consumer.kafka.KafkaConsumer.handleCircularNoFlyZone (String message)
References com.capstone.shared.JsonHelper.fromJson(), com.capstone.consumer.servicehandler.NoFlyZoneService.storeNoFlyZone(), and com.capstone.consumer.servicehandler.LiveTrackingService.trackNewNoFlyZone().
handleFlightUpdate()
void com.capstone.consumer.kafka.KafkaConsumer.handleFlightUpdate (String message)
References com.capstone.shared.JsonHelper.fromJson(), com.capstone.consumer.servicehandler.FlightLocationService.upsertFlightInformation(), and com.capstone.consumer.servicehandler.LiveTrackingService.upsertFlightInformation().
handlePolygonNoFlyZone()
void com.capstone.consumer.kafka.KafkaConsumer.handlePolygonNoFlyZone (String message)
References com.capstone.shared.JsonHelper.fromJson(), com.capstone.consumer.servicehandler.NoFlyZoneService.storeNoFlyZone(), and com.capstone.consumer.servicehandler.LiveTrackingService.trackNewNoFlyZone().
The documentation for this class was generated from the following file:
C:/Users/Bits McGee/Documents/GitHub/FlightTrackerConsumer/src/main/java/com/capstone/consumer/kafka/KafkaConsumer.java