My Project: com.capstone.consumer.bindings.FlightInformation Class Reference
com.capstone.consumer.bindings.FlightInformation Class Reference
Public Member Functions
FlightInformation setCheckPoints (List< Double > checkPoints)
LineString getGeometry ()
Member Function Documentation
getGeometry()
LineString com.capstone.consumer.bindings.FlightInformation.getGeometry ()
References com.capstone.consumer.utils.GeoUtils.geometryFactory.
Referenced by com.capstone.consumer.utils.GeoUtils.getFlightIntersectionWithNoFlyZone().
setCheckPoints()
FlightInformation com.capstone.consumer.bindings.FlightInformation.setCheckPoints (List< Double > checkPoints)
Referenced by com.capstone.consumer.servicehandler.LiveTrackingService.createInternalFlight(), and com.capstone.consumer.messages.FlightPathUpdatedMessage.FlightPathUpdatedMessage().
The documentation for this class was generated from the following file:
C:/Users/Bits McGee/Documents/GitHub/FlightTrackerConsumer/src/main/java/com/capstone/consumer/bindings/FlightInformation.java