name: Release Docker Image

env:
  SONAR_TOKEN: ${{secrets.SONAR_TOKEN}}
  SONAR_HOST_URL: ${{secrets.SONAR_HOST_URL}}

  AWS_DEFAULT_REGION: us-east-1
  AWS_ECR_ARN: ${{secrets.AWS_ECR_ARN}}
  AWS_ACCESS_KEY_ID: ${{secrets.AWS_ECR_ACCESS_KEY}}
  AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_ECR_ACCESS_KEY_SECRET}}

  DOCKERHUB_ACCESS_TOKEN: ${{secrets.DOCKERHUB_ACCESS_TOKEN}}

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Cache SonarQube packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Start Test Apache Kafka Instance
        run: |
          docker compose -f docker-compose.yml up -d --quiet-pull
          sleep 10s

      - name: Build with Maven
        run: |
          mvn -B package --file pom.xml > void.txt
          BUILD_NUMBER=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "BUILD_NUMBER=${BUILD_NUMBER}" >> $GITHUB_ENV 
          cat $GITHUB_ENV

      - name: Build and Analyze
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        run: mvn --quiet -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=consumer

      - name: Authenticate to docker
        run : |
          aws ecr get-login-password | docker login --username AWS --password-stdin $AWS_ECR_ARN 

      - name: Build and Publish Docker Image
        run : |
          docker build -t flight-tracker-consumer . --build-arg="build_type=prod"
          docker tag flight-tracker-consumer:latest 058264501037.dkr.ecr.us-east-1.amazonaws.com/flight-tracker-consumer:${BUILD_NUMBER}
          docker push 058264501037.dkr.ecr.us-east-1.amazonaws.com/flight-tracker-consumer:${BUILD_NUMBER}
          docker logout AWS

      - name: Authenticate to dockerhub
        run : |
          docker login -u ewagner2802 --password $DOCKERHUB_ACCESS_TOKEN

      - name: Build and Publish Docker Image to dockerhub
        run : |
          docker tag flight-tracker-consumer:latest ewagner2802/flighttrackerconsumer:${BUILD_NUMBER}
          docker tag flight-tracker-consumer:latest ewagner2802/flighttrackerconsumer:latest
          
          docker push ewagner2802/flighttrackerconsumer --all-tags

